apiVersion: v1
kind: Service
metadata:
  name: connect
spec:
  type: ClusterIP
  selector:
    app: connect
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
